spring:
  redis:
    host: 43.140.197.50
    port: 6379
    password: Xjs02220012
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  datasource:
    url: jdbc:mysql://localhost:3306/online_judge?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Xjs02220012

path:
  user: D:/code/OnlineJudgeSource/user
  problem: D:/code/OnlineJudgeSource/problem