spring:
  application:
    name: DocumentRetrievalManagementSystem
  profiles:
    active: dev
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: x1730523754@163.com
    password: LNDVYMKMOTSTAVPC
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
aliyun:
  oss:
    access-key-id: LTAI5tH6HKinBooaELQiKn4R
    access-key-secret: vU2wTbDgSHLQIr52ZlLaOCCukh3WwH
    bucket-name: web-advertisement
    endpoint: https://oss-cn-hangzhou.aliyuncs.com


server:
  port: 8070

#mybatis:
#  mapper-locations: classpath:mappers/*xml
#  type-aliases-package: com.project.documentretrievalmanagementsystem.mybatis.entity

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*Mapper.xml