spring:
  redis:
    host: 43.140.197.50
    port: 6379
    password: Xjs02220012
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  datasource:
    url: jdbc:mysql://43.140.197.50:3306/online_judge?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Xjs02220012
    # 连接池
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 60
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 180000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#path:
#  user: /usr/local/java/JavaProject/OnlineJudge/OnlineJudgeSource/user
#  problem: /usr/local/java/JavaProject/OnlineJudge/OnlineJudgeSource/problem
path:
  user: D:/code/OnlineJudgeSource/user
  problem: D:/code/OnlineJudgeSource/problem