spring:
  application:
    name: DocumentRetrievalManagementSystem
  profiles:
    active: dev
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: x1730523754@163.com
    password: LNDVYMKMOTSTAVPC
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          port: 465

server:
  port: 8070

#mybatis:
#  mapper-locations: classpath:mappers/*xml
#  type-aliases-package: com.project.documentretrievalmanagementsystem.mybatis.entity

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*Mapper.xml